'use client';

import * as React from 'react';

/**
 * Cmd+K search dialog — backed by Pagefind (static, client-side, WASM;
 * https://pagefind.app), not a build-time index prop. `/_pagefind/pagefind.js`
 * is generated by the consuming app's postbuild step (see the package
 * README's "Search (Pagefind)" section) and dynamically imported here at
 * runtime; if it's missing (dev mode, or a consumer that skipped the
 * postbuild step) the dialog degrades to an "index unavailable" message
 * instead of crashing.
 *
 * The active query is reflected in the URL as repeated `?q=` params (one per
 * word — matches how Pagefind's own highlight script reads `?q=` via
 * URLSearchParams.getAll, see pagefind-highlight-mount.tsx) via
 * history.replaceState while typing, so a search-in-progress is shareable
 * and a `?q=`-bearing URL re-opens the dialog pre-filled on load (deep-link
 * into results). Clicking a result carries the same `?q=` to the destination
 * page so PagefindHighlightMount can highlight the term(s) there.
 */

type PagefindSearchResult = {
  id: string;
  data: () => Promise<{ url: string; meta: { title?: string }; excerpt: string }>;
};

type PagefindModule = {
  init?: () => Promise<void> | void;
  search: (query: string) => Promise<{ results: PagefindSearchResult[] }>;
};

type Result = { url: string; title: string; excerpt: string };

const QUERY_PARAM = 'q';

let pagefindPromise: Promise<PagefindModule | null> | null = null;

// Loaded via a runtime-injected <script type="module"> whose *text content*
// (not a bundler-visible import() call) does the import — this is the only
// approach that reliably survives Turbopack's build-time module resolution.
// A plain import('/_pagefind/pagefind.js') (even wrapped in a non-literal
// variable, even with webpackIgnore/turbopackIgnore comments) still made
// Turbopack fail the build with "Module not found: Can't resolve
// './_pagefind/pagefind.js' — server relative imports are not implemented
// yet" (confirmed while testing this integration) — Turbopack statically
// traces the specifier regardless. A <script> tag's textContent is opaque
// to the bundler (it's just a string), so the import inside it is only ever
// resolved by the browser's native ES module loader, at runtime.
function loadPagefindViaScriptTag(): Promise<PagefindModule | null> {
  return new Promise((resolve) => {
    const script = document.createElement('script');
    script.type = 'module';
    script.textContent = [
      "import * as pagefind from '/_pagefind/pagefind.js';",
      'window.__inkformPagefindModule = pagefind;',
      "window.dispatchEvent(new Event('inkform:pagefind-loaded'));",
    ].join('\n');
    window.addEventListener(
      'inkform:pagefind-loaded',
      () => {
        resolve((window as unknown as { __inkformPagefindModule?: PagefindModule }).__inkformPagefindModule ?? null);
      },
      { once: true },
    );
    script.onerror = () => resolve(null); // index missing (dev mode, or postbuild wasn't run) — degrade gracefully
    document.head.appendChild(script);
  });
}

/** Lazily loads the build-generated Pagefind module. Cached — only fetched once per page load. */
function loadPagefind(): Promise<PagefindModule | null> {
  if (!pagefindPromise) {
    pagefindPromise = loadPagefindViaScriptTag().then(async (mod) => {
      if (!mod) return null;
      await mod.init?.();
      return mod;
    });
  }
  return pagefindPromise;
}

function wordsFromQuery(q: string): string[] {
  return q.trim().split(/\s+/).filter(Boolean);
}

function readQueryParam(): string {
  if (typeof window === 'undefined') return '';
  return new URLSearchParams(window.location.search).getAll(QUERY_PARAM).join(' ');
}

/** Reflects the query as repeated `?q=` params without creating a history entry per keystroke. */
function syncQueryParam(value: string) {
  const url = new URL(window.location.href);
  url.searchParams.delete(QUERY_PARAM);
  for (const w of wordsFromQuery(value)) url.searchParams.append(QUERY_PARAM, w);
  window.history.replaceState(window.history.state, '', url.toString());
}

/** Builds a destination URL carrying the query for PagefindHighlightMount to pick up. */
function withQueryParam(url: string, value: string): string {
  const dest = new URL(url, typeof window === 'undefined' ? 'http://localhost' : window.location.origin);
  dest.searchParams.delete(QUERY_PARAM);
  for (const w of wordsFromQuery(value)) dest.searchParams.append(QUERY_PARAM, w);
  return dest.pathname + dest.search + dest.hash;
}

export function SearchDialog({
  placeholder = 'Search…',
  minQueryLength = 2,
}: {
  placeholder?: string;
  minQueryLength?: number;
}) {
  const [open, setOpen] = React.useState(false);
  const [q, setQ] = React.useState('');
  const [results, setResults] = React.useState<Result[]>([]);
  const [active, setActive] = React.useState(0);
  const [indexUnavailable, setIndexUnavailable] = React.useState(false);
  const inputRef = React.useRef<HTMLInputElement>(null);

  // Deep-link: a `?q=` already in the URL on load re-opens the dialog pre-filled.
  React.useEffect(() => {
    const initial = readQueryParam();
    if (initial) {
      setQ(initial);
      setOpen(true);
    }
  }, []);

  React.useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') {
        e.preventDefault();
        setOpen((o) => !o);
      } else if (e.key === 'Escape') setOpen(false);
    }
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  React.useEffect(() => {
    if (open) requestAnimationFrame(() => inputRef.current?.focus());
  }, [open]);

  React.useEffect(() => setActive(0), [results]);

  // Query -> Pagefind results (debounced) + URL sync while the dialog is open.
  React.useEffect(() => {
    if (!open) return;
    syncQueryParam(q);

    if (wordsFromQuery(q).length === 0 || q.trim().length < minQueryLength) {
      setResults([]);
      return;
    }

    let cancelled = false;
    const timer = setTimeout(async () => {
      const pagefind = await loadPagefind();
      if (cancelled) return;
      if (!pagefind) {
        setIndexUnavailable(true);
        return;
      }
      setIndexUnavailable(false);
      const { results: hits } = await pagefind.search(q);
      if (cancelled) return;
      const data = await Promise.all(hits.slice(0, 12).map((r) => r.data()));
      if (cancelled) return;
      setResults(data.map((d) => ({ url: d.url, title: d.meta.title ?? d.url, excerpt: d.excerpt })));
    }, 120);

    return () => {
      cancelled = true;
      clearTimeout(timer);
    };
  }, [q, open, minQueryLength]);

  function goTo(url: string) {
    window.location.href = withQueryParam(url, q);
  }

  const belowMinLength = wordsFromQuery(q).length > 0 && q.trim().length < minQueryLength;

  return (
    <>
      <button type="button" className="fw-search-trigger" onClick={() => setOpen(true)} aria-label="Search">
        Search <kbd>⌘K</kbd>
      </button>
      {open ? (
        <div className="fw-search-overlay" role="dialog" aria-modal onClick={() => setOpen(false)}>
          <div className="fw-search-panel" onClick={(e) => e.stopPropagation()}>
            <input
              ref={inputRef}
              className="fw-search-input"
              value={q}
              placeholder={placeholder}
              onChange={(e) => setQ(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'ArrowDown') {
                  e.preventDefault();
                  setActive((a) => Math.min(a + 1, results.length - 1));
                } else if (e.key === 'ArrowUp') {
                  e.preventDefault();
                  setActive((a) => Math.max(a - 1, 0));
                } else if (e.key === 'Enter' && results[active]) {
                  goTo(results[active].url);
                }
              }}
            />
            <ul className="fw-search-results">
              {indexUnavailable ? (
                <li className="fw-search-empty">Search index unavailable — run a production build to enable search.</li>
              ) : belowMinLength ? (
                <li className="fw-search-empty">Keep typing to search…</li>
              ) : wordsFromQuery(q).length === 0 ? (
                <li className="fw-search-empty">Type to search…</li>
              ) : results.length === 0 ? (
                <li className="fw-search-empty">No results for “{q}”</li>
              ) : (
                results.map((r, i) => (
                  <li key={r.url}>
                    <a
                      href={r.url}
                      data-active={i === active}
                      onMouseEnter={() => setActive(i)}
                      onClick={(e) => {
                        e.preventDefault();
                        goTo(r.url);
                      }}
                    >
                      <span className="fw-search-result-title">{r.title}</span>
                      {/* Pagefind's own excerpt already wraps matches in <mark> — safe, generated
                          from our own indexed content, not user input. */}
                      <span className="fw-search-result-excerpt" dangerouslySetInnerHTML={{ __html: r.excerpt }} />
                    </a>
                  </li>
                ))
              )}
            </ul>
          </div>
        </div>
      ) : null}
    </>
  );
}
